# practicing data cleaning and column transformations

In [14]:
import pandas as pd
import numpy as np

In [15]:
data = pd.read_csv('test.csv')
df = pd.DataFrame(data)
df.head()

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfied

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25976 entries, 0 to 25975
Data columns (total 25 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         25976 non-null  int64
 1   id                                 25976 non-null  int64
 2   Gender                             25976 non-null  object
 3   Customer Type                      25976 non-null  object
 4   Age                                25976 non-null  int64
 5   Type of Travel                     25976 non-null  object
 6   Class                              25976 non-null  object
 7   Flight Distance                    25976 non-null  int64
 8   Inflight wifi service              25976 non-null  int64
 9   Departure/Arrival time convenient  25976 non-null  int64
 10  Ease of Online booking             25976 non-null  int64
 11  Gate location                      25976 non-null  int64
 12  Food and drink                     25976 non-null  int64
 13  Online boarding                    25976 non-null  int64
 14  Seat comfort                       25976 non-null  int64
 15  Inflight entertainment             25976 non-null  int64
 16  On-board service                   25976 non-null  int64
 17  Leg room service                   25976 non-null  int64
 18  Baggage handling                   25976 non-null  int64
 19  Checkin service                    25976 non-null  int64
 20  Inflight service                   25976 non-null  int64
 21  Cleanliness                        25976 non-null  int64
 22  Departure Delay in Minutes         25976 non-null  int64
 23  Arrival Delay in Minutes           25893 non-null  float64
 24  satisfaction                       25976 non-null  object
dtypes: float64(1), int64(19), object(5)
memory usage: 5.0+ MB

In [17]:
df.isnull().sum()

Unnamed: 0                            0
id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             83
satisfaction                          0
dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    df.drop(columns=['satisfaction']),
    df['satisfaction'],
    test_size=0.1
)

In [19]:
x_train

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
25626,25626,97675,Male,Loyal Customer,45,Personal Travel,Eco,272,4,0,...,2,2,4,5,3,1,4,2,0,0.0
3478,3478,111623,Female,Loyal Customer,40,Personal Travel,Eco,1014,2,5,...,4,4,2,1,4,3,3,4,15,34.0
4106,4106,94866,Female,disloyal Customer,44,Business travel,Eco,239,3,4,...,3,3,2,2,3,1,4,3,105,98.0
2139,2139,102558,Female,Loyal Customer,8,Personal Travel,Eco,236,1,4,...,3,3,5,5,5,5,5,3,9,14.0
6855,6855,40857,Male,Loyal Customer,30,Personal Travel,Eco,541,3,4,...,4,4,3,3,5,5,5,4,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2517,2517,8654,Male,Loyal Customer,51,Business travel,Business,2572,3,3,...,4,4,4,4,4,3,4,5,6,0.0
5976,5976,53351,Male,disloyal Customer,46,Business travel,Eco,908,4,4,...,3,3,5,4,5,2,5,3,37,46.0
12599,12599,97144,Male,disloyal Customer,14,Business travel,Eco,1497,2,2,...,1,1,2,1,3,2,3,1,85,70.0
12997,12997,30475,Male,disloyal Customer,27,Business travel,Eco,377,3,4,...,5,2,4,1,4,2,5,2,0,0.0
12348,12348,24450,Male,Loyal Customer,32,Business travel,Business,2266,2,5,...,5,5,1,5,1,1,1,5,4,30.0

In [7]:
df['Type of Travel'].unique()

array(['Business travel', 'Personal Travel'], dtype=object)

In [8]:
df['Customer Type'].unique()

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [9]:
df['Class'].unique()

array(['Eco', 'Business', 'Eco Plus'], dtype=object)

# performed ordinal encoding

In [20]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Eco', 'Business', 'Eco Plus']])

In [21]:
x_train[['Class']] = oe.fit_transform(x_train[['Class']])
x_test[['Class']] = oe.transform(x_test[['Class']])

In [22]:
x_train

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
25626,25626,97675,Male,Loyal Customer,45,Personal Travel,0.0,272,4,0,...,2,2,4,5,3,1,4,2,0,0.0
3478,3478,111623,Female,Loyal Customer,40,Personal Travel,0.0,1014,2,5,...,4,4,2,1,4,3,3,4,15,34.0
4106,4106,94866,Female,disloyal Customer,44,Business travel,0.0,239,3,4,...,3,3,2,2,3,1,4,3,105,98.0
2139,2139,102558,Female,Loyal Customer,8,Personal Travel,0.0,236,1,4,...,3,3,5,5,5,5,5,3,9,14.0
6855,6855,40857,Male,Loyal Customer,30,Personal Travel,0.0,541,3,4,...,4,4,3,3,5,5,5,4,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2517,2517,8654,Male,Loyal Customer,51,Business travel,1.0,2572,3,3,...,4,4,4,4,4,3,4,5,6,0.0
5976,5976,53351,Male,disloyal Customer,46,Business travel,0.0,908,4,4,...,3,3,5,4,5,2,5,3,37,46.0
12599,12599,97144,Male,disloyal Customer,14,Business travel,0.0,1497,2,2,...,1,1,2,1,3,2,3,1,85,70.0
12997,12997,30475,Male,disloyal Customer,27,Business travel,0.0,377,3,4,...,5,2,4,1,4,2,5,2,0,0.0
12348,12348,24450,Male,Loyal Customer,32,Business travel,1.0,2266,2,5,...,5,5,1,5,1,1,1,5,4,30.0

In [25]:

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [26]:
le.fit(y_train)

LabelEncoder()

In [27]:
le.classes_

array(['neutral or dissatisfied', 'satisfied'], dtype=object)

In [28]:

y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [29]:
y_test

array([1, 0, 0, ..., 1, 0, 0])

# nominal encoding

In [31]:
# using pandas K-1 OneHotEncoding
pd.get_dummies(df,columns=['Gender','Customer Type','Type of Travel'],drop_first=True)

,Unnamed: 0,id,Age,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,...,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel
0,0,19556,52,Eco,160,5,4,3,4,3,...,5,2,5,5,50,44.0,satisfied,False,False,False
1,1,90035,36,Business,2863,1,1,3,1,5,...,4,3,4,5,0,0.0,satisfied,False,False,False
2,2,12360,20,Eco,192,2,0,2,4,2,...,3,2,2,2,0,0.0,neutral or dissatisfied,True,True,False
3,3,77959,44,Business,3377,0,0,0,2,3,...,1,3,1,4,0,6.0,satisfied,True,False,False
4,4,36875,49,Eco,1182,2,3,4,3,4,...,2,4,2,4,0,20.0,satisfied,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25971,25971,78463,34,Business,526,3,3,3,1,4,...,4,4,5,4,0,0.0,neutral or dissatisfied,True,True,False
25972,25972,71167,23,Business,646,4,4,4,4,4,...,5,5,5,4,0,0.0,satisfied,True,False,False
25973,25973,37675,17,Eco,828,2,5,1,5,2,...,4,5,4,2,0,0.0,neutral or dissatisfied,False,False,True
25974,25974,90086,14,Business,1127,3,3,3,3,4,...,5,4,5,4,0,0.0,satisfied,True,False,False
25975,25975,34799,42,Eco,264,2,5,2,5,4,...,1,1,1,1,0,0.0,neutral or dissatisfied,False,False,True

In [44]:
# OneHotEncoding using Sklearn
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse_output=True,dtype=np.int32)
X_train_new = ohe.fit_transform(x_train[['Gender','Customer Type','Type of Travel']])
X_test_new = ohe.transform(x_test[['Gender','Customer Type','Type of Travel']])

In [47]:
df.columns

Index(['Unnamed: 0', 'id', 'Gender', 'Customer Type', 'Age', 'Type of Travel',
       'Class', 'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [48]:
numeric_cols = ['Unnamed: 0', 'id', 'Age', 'Class', 'Flight Distance',
                'Inflight wifi service','Departure/Arrival time convenient',
                'Ease of Online booking','Gate location','Food and drink',
                'Online boarding','Seat comfort','Inflight entertainment',
                'On-board service','Leg room service','Baggage handling',
                'Checkin service','Inflight service','Cleanliness',
                'Departure Delay in Minutes','Arrival Delay in Minutes']

# One-hot feature names
ohe_feature_names = ohe.get_feature_names_out(['Gender','Customer Type','Type of Travel'])
X_train_final = pd.DataFrame(np.hstack((x_train[numeric_cols].values, X_train_new.toarray())),
                             columns=numeric_cols + list(ohe_feature_names),
                             index=x_train.index)

X_test_final = pd.DataFrame(np.hstack((x_test[numeric_cols].values, X_test_new.toarray())),
                            columns=numeric_cols + list(ohe_feature_names),
                            index=x_test.index)

In [55]:
X_train_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23378 entries, 25626 to 12348
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         23378 non-null  float64
 1   id                                 23378 non-null  float64
 2   Age                                23378 non-null  float64
 3   Class                              23378 non-null  float64
 4   Flight Distance                    23378 non-null  float64
 5   Inflight wifi service              23378 non-null  float64
 6   Departure/Arrival time convenient  23378 non-null  float64
 7   Ease of Online booking             23378 non-null  float64
 8   Gate location                      23378 non-null  float64
 9   Food and drink                     23378 non-null  float64
 10  Online boarding                    23378 non-null  float64
 11  Seat comfort                       23378 non-null  float64
 12  Inflight entertainment             23378 non-null  float64
 13  On-board service                   23378 non-null  float64
 14  Leg room service                   23378 non-null  float64
 15  Baggage handling                   23378 non-null  float64
 16  Checkin service                    23378 non-null  float64
 17  Inflight service                   23378 non-null  float64
 18  Cleanliness                        23378 non-null  float64
 19  Departure Delay in Minutes         23378 non-null  float64
 20  Arrival Delay in Minutes           23306 non-null  float64
 21  Gender_Male                        23378 non-null  float64
 22  Customer Type_disloyal Customer    23378 non-null  float64
 23  Type of Travel_Personal Travel     23378 non-null  float64
dtypes: float64(24)
memory usage: 4.5 MB

In [58]:
X_train_final = X_train_final.fillna(0).astype('int32')
X_test_final  = X_test_final.fillna(0).astype('int32')

In [60]:
X_train_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23378 entries, 25626 to 12348
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Unnamed: 0                         23378 non-null  int32
 1   id                                 23378 non-null  int32
 2   Age                                23378 non-null  int32
 3   Class                              23378 non-null  int32
 4   Flight Distance                    23378 non-null  int32
 5   Inflight wifi service              23378 non-null  int32
 6   Departure/Arrival time convenient  23378 non-null  int32
 7   Ease of Online booking             23378 non-null  int32
 8   Gate location                      23378 non-null  int32
 9   Food and drink                     23378 non-null  int32
 10  Online boarding                    23378 non-null  int32
 11  Seat comfort                       23378 non-null  int32
 12  Inflight entertainment             23378 non-null  int32
 13  On-board service                   23378 non-null  int32
 14  Leg room service                   23378 non-null  int32
 15  Baggage handling                   23378 non-null  int32
 16  Checkin service                    23378 non-null  int32
 17  Inflight service                   23378 non-null  int32
 18  Cleanliness                        23378 non-null  int32
 19  Departure Delay in Minutes         23378 non-null  int32
 20  Arrival Delay in Minutes           23378 non-null  int32
 21  Gender_Male                        23378 non-null  int32
 22  Customer Type_disloyal Customer    23378 non-null  int32
 23  Type of Travel_Personal Travel     23378 non-null  int32
dtypes: int32(24)
memory usage: 2.3 MB